# Generated by Django 4.0 on 2021-12-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='Body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_created',
            new_name='DateCreated',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='Slug',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='Title',
        ),
    ]
