# Generated by Django 4.0 on 2021-12-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_body_article_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
