# Generated by Django 4.0 on 2021-12-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='DateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Title',
            new_name='title',
        ),
    ]
